name: Build
on:
  push:
    branches: [main]
  pull_request:
env:
  AWS_ACCOUNT_ID: 336241431902
  AWS_REGION: eu-central-1
jobs:
  build:
    runs-on: shared-service
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
  docker:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [build]
    runs-on: shared-service
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ env.AWS_ACCOUNT_ID }}
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: digibank/images/apollo
          IMAGE_TAG: "${{ github.run_number }}"
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
